name: .NET Core Desktop

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest
    env:
      App_Name: PathManager
      Solution_Path: PathManager.sln
      App_Project_Path: PathManager/PathManager.csproj
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Restore before build and test
    - name: Restore
      run: dotnet restore ${{ env.Solution_Path }}

    - name: Build with dotnet
      run: dotnet build ${{ env.App_Project_Path }} --no-restore
      env:
        Configuration: ${{ matrix.configuration }}

    # Execute all unit tests in the solution
    #- name: Execute unit tests
    #  run: dotnet test --no-restore

  release:
    runs-on: windows-latest
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/') # Run only when a tag is changed

    env:
      App_Name: PathManager
      Solution_Path: PathManager.sln
      App_Project_Path: PathManager/PathManager.csproj
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Publish (Self-Contained, only for win-x64 for now)
      run: dotnet publish -c Release -r win-x64 --self-contained true -o ./release

    - name: Create ZIP archive
      shell: pwsh
      run: Compress-Archive -Path ./release/* -DestinationPath release.zip

    - name: Create Release and Upload Asset
      uses: softprops/action-gh-release@v2
      with:
        files: release.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        
